/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deporteysalud;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
/**
 *
 * @author Skyth
 */
public class Intermedio1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Intermedio1.class.getName());

    /**
     * Creates new form Avanzado
     */
    public Intermedio1() {
        initComponents();
        personalizarEstilo();
        
        addComponentListener(new java.awt.event.ComponentAdapter() { //Escucha componentes, en este caso a la ventana cuando se redimensiona
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            escalarTexto();   // Método que tú definirás
        }
    });
    }

     private void personalizarEstilo() {
        // Fondo oscuro del panel
        jPanel1.setBackground(new Color(45, 45, 45));

        // Borde del panel
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2));

        // Personalizar texto
        javax.swing.JLabel[] etiquetas = {
            jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7
        };

        for (javax.swing.JLabel label : etiquetas) {
            label.setForeground(Color.WHITE);
            label.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    Menu1 menu = new Menu1();
    menu.setVisible(true);
    this.dispose(); // cierra la ventana actual
}
    private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();  // Nuevo botón

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Entrenamiento Principiante");
    setResizable(true);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    javax.swing.JLabel[] etiquetas = {
        jLabel1, jLabel7, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6
    };
    String[] textos = {
        "Entrenamiento",
        "Sentadillas con peso Corporal",
        "Flexiones de Brazos",
        "Zancadas Alternas",
        "Remo con bandas elásticas",
        "Plancha",
        "Saltos en Tijera"
    };

    for (int i = 0; i < etiquetas.length; i++) {
        etiquetas[i].setText(textos[i]);
        etiquetas[i].setForeground(java.awt.Color.WHITE);
        etiquetas[i].setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        etiquetas[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = i;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);

        jPanel1.add(etiquetas[i], gridBagConstraints);
    }

    // ======= BOTÓN NUEVO =======
    jButton1.setText("Volver");
    jButton1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    jButton1.setBackground(new java.awt.Color(70, 130, 180));
    jButton1.setForeground(java.awt.Color.WHITE);
    jButton1.setFocusPainted(false);

    jButton1.addActionListener(this::jButton1ActionPerformed);
        // Aquí puedes agregar lógica para iniciar el entrenamiento, abrir otra ventana, etc.
    

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = etiquetas.length;  // Añadir debajo de las etiquetas
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);

    jPanel1.add(jButton1, gridBagConstraints);

    jPanel1.setBackground(new java.awt.Color(45, 45, 45));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.LIGHT_GRAY, 2));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    setMinimumSize(new java.awt.Dimension(400, 400));
    pack();
    setLocationRelativeTo(null);
    }   
    
    private void escalarTexto() {
    int ancho = getWidth();
    int alto = getHeight();
    
    // Calcular tamaño de fuente basado en el tamaño de la ventana
    int nuevoTamaño = Math.max(12, Math.min(ancho, alto) / 25); // ajusta el divisor según tu diseño

    Font nuevaFuente = new Font("Segoe UI", Font.PLAIN, nuevoTamaño);
    Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, nuevoTamaño + 2);

    // Aplicar la nueva fuente
    jLabel1.setFont(fuenteTitulo);  // Título
    jLabel1.setForeground(Color.WHITE);

    javax.swing.JLabel[] etiquetas = {
        jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7
    };

    for (javax.swing.JLabel label : etiquetas) {
        label.setFont(nuevaFuente);
        label.setForeground(Color.WHITE);
    }

    // También puedes escalar el botón
    jButton1.setFont(new Font("Segoe UI", Font.BOLD, nuevoTamaño));
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
            }
        }
        } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

          java.awt.EventQueue.invokeLater(() -> new Intermedio1().setVisible(true));
        }
    
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JButton jButton1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
