/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deporteysalud;

import java.awt.*;
import javax.swing.*;
import java.net.URL;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.GridBagConstraints;
import java.awt.Insets;
/**
 *
 * @author Skyth
 */
public class Menu1 extends javax.swing.JFrame {
    
    private JPanel jPanel1;
    private JLabel jLabelTitulo1;
    private JLabel jLabelTitulo2;
    private JLabel jLabelEntrenamientos;
    private JLabel jLabelIMC;
    private JButton btnPrincipiante;
    private JButton btnIntermedio;
    private JButton btnAvanzado;
    private JButton btnIMC;
    private JLabel lblImagen; // para la imagen en la parte superior
    private Image imagenOriginal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu1.class.getName());

    /**
     * Creates new form Menu1
     * 
     * 
     */
    
    private void escalarTexto() {
        int ancho = getWidth();
        int alto = getHeight();
        int tamañoBase = Math.max(12, Math.min(ancho, alto) / 25);
        int tamañoTitulo = tamañoBase + 2;

        Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, tamañoTitulo);
        Font fuenteNormal = new Font("Segoe UI", Font.PLAIN, tamañoBase);

        jLabelTitulo1.setFont(fuenteTitulo);
        jLabelTitulo2.setFont(fuenteTitulo);
        jLabelEntrenamientos.setFont(fuenteNormal);
        jLabelIMC.setFont(fuenteNormal);

        JButton[] botones = { btnPrincipiante, btnIntermedio, btnAvanzado, btnIMC };
        for (JButton boton : botones) {
            boton.setFont(fuenteNormal);
        }
    }
    
    public Menu1() {
        initComponents();
    cargarImagenDesdeInternet();  // en lugar de cargarImagen();
    escalarTexto();
    
    addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            escalarTexto();
            actualizarImagen(); // también actualizar la imagen al redimensionar
        }
    });
    actualizarImagen(); // para mostrar imagen inicialmente
    }

    
   private void cargarImagenDesdeInternet() {
    try {
        URL url = new URL("https://img.freepik.com/psd-gratis/plantilla-banner-web-gimnasios-gimnasios_106176-674.jpg?semt=ais_hybrid&w=740&q=80");  // Pon aquí tu URL
        imagenOriginal = ImageIO.read(url);
        lblImagen = new JLabel();
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setOpaque(false);

        // Añadir la etiqueta de imagen al panel
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.weighty = 0.3;

        jPanel1.add(lblImagen, gbc);
    } catch (IOException e) {
        System.err.println("Error al cargar la imagen desde la URL: " + e.getMessage());
    }
}

// Método para actualizar el tamaño de la imagen
private void actualizarImagen() {
        if (imagenOriginal != null && lblImagen.getWidth() > 0 && lblImagen.getHeight() > 0) {
        Image imgEscalada = imagenOriginal.getScaledInstance(
            lblImagen.getWidth(),
            lblImagen.getHeight(),
            Image.SCALE_SMOOTH
        );
        lblImagen.setIcon(new ImageIcon(imgEscalada));
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    Principiante1 principiante = new Principiante1();
    principiante.setVisible(true);
    this.dispose(); // cierra la ventana actual
    }
    
    private void initComponents() {
        GridBagConstraints gbc;

        jPanel1 = new JPanel();
        jPanel1.setBackground(new Color(45, 45, 45));
        jPanel1.setLayout(new GridBagLayout());

        jLabelTitulo1 = new JLabel("Tienes Una Cita...");
        jLabelTitulo2 = new JLabel("Con tu Salud");
        jLabelEntrenamientos = new JLabel("Entrenamientos");
        jLabelIMC = new JLabel("Calcula el IMC");

        Color blanco = Color.WHITE;
        jLabelTitulo1.setForeground(blanco);
        jLabelTitulo2.setForeground(blanco);
        jLabelEntrenamientos.setForeground(blanco);
        jLabelIMC.setForeground(blanco);

        btnPrincipiante = new JButton("Principiante");
        btnIntermedio = new JButton("Intermedio");
        btnAvanzado = new JButton("Avanzado");
        btnIMC = new JButton("Ir");

        // TITULOS
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(10, 10, 5, 10);
        gbc.anchor = GridBagConstraints.CENTER;
        jPanel1.add(jLabelTitulo1, gbc);

        gbc.gridy = 2;
        gbc.insets = new Insets(0, 10, 20, 10);
        jPanel1.add(jLabelTitulo2, gbc);

        // SUBTITULOS
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.gridx = 0;
        jPanel1.add(jLabelEntrenamientos, gbc);

        gbc.gridx = 1;
        jPanel1.add(jLabelIMC, gbc);

        // PANEL BOTONES ENTRENAMIENTOS
        JPanel panelEntrenamientos = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 0));
        panelEntrenamientos.setOpaque(false);
        panelEntrenamientos.add(btnPrincipiante);
        panelEntrenamientos.add(btnIntermedio);
        panelEntrenamientos.add(btnAvanzado);

        gbc.gridy = 4;
        gbc.gridx = 0;
        jPanel1.add(panelEntrenamientos, gbc);

        // PANEL BOTON IMC
        JPanel panelIMC = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelIMC.setOpaque(false);
        panelIMC.add(btnIMC);

        gbc.gridx = 1;
        jPanel1.add(panelIMC, gbc);

        // ACCIONES
        btnPrincipiante.addActionListener(evt -> {
            new Principiante1().setVisible(true);
            dispose();
        });
        btnIntermedio.addActionListener(evt -> {
            new Intermedio1().setVisible(true);
            dispose();
        });
        btnAvanzado.addActionListener(evt -> {
            new Avanzado1().setVisible(true);
            dispose();
        });
        btnIMC.addActionListener(evt -> {
            new IMC1().setVisible(true);
            dispose();
        });

        // VENTANA PRINCIPAL
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanel1));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanel1));

        setMinimumSize(new Dimension(600, 500));
        pack();
        setLocationRelativeTo(null);
    }
    @SuppressWarnings("unchecked")/*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        EventQueue.invokeLater(() -> new Menu1().setVisible(true));
    }
        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

