/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deporteysalud;

import java.awt.*;
import javax.swing.*;

import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.util.IOUtils;
import org.apache.poi.ss.usermodel.ClientAnchor;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Drawing;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.awt.Font;
import java.io.InputStream;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Image;
import com.itextpdf.text.pdf.PdfWriter;






/**
 *
 * @author Skyth
 */
public class IMC1 extends javax.swing.JFrame {
    
    
    private JComboBox<String> comboPeso;
    private JComboBox<String> comboAltura;
    private JComboBox<String> comboEdad;
    private JButton btnCalcular;
    private JButton btnVolver;
    private JLabel lblResultado;
    private JLabel lblTitulo, lblPeso, lblAltura, lblEdad;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IMC1.class.getName());

    /**
     * Creates new form IMC1
     */
    public IMC1() {
        initComponents();
         escalarTexto();

        // Escalar al cambiar el tamaño
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                escalarTexto();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    */
    
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora IMC");
        setMinimumSize(new Dimension(500, 400));
        getContentPane().setBackground(Color.BLACK);
        getContentPane().setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();

        // Titulo
        lblTitulo = new JLabel("Calculadora de IMC");
        lblTitulo.setForeground(Color.WHITE);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(10, 10, 20, 10);
        gbc.anchor = GridBagConstraints.CENTER;
        getContentPane().add(lblTitulo, gbc);

        
        // Etiqueta Edad
        lblEdad = new JLabel("Edad :");
        lblEdad.setForeground(Color.WHITE);
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.insets = new Insets(5, 10, 5, 10);
        getContentPane().add(lblEdad, gbc);

        // ComboBox Edad
        comboEdad = new JComboBox<>();
        for (double i = 1; i <= 100; i += 1) {
            comboEdad.addItem(String.format("%.1f", i));
        }
        gbc.gridx = 1;
        getContentPane().add(comboEdad, gbc);
        
        
        // Etiqueta Peso
        lblPeso = new JLabel("Peso (kg):");
        lblPeso.setForeground(Color.WHITE);
        gbc.gridy = 2;
        gbc.gridx = 0;
        gbc.gridwidth = 1;
        gbc.insets = new Insets(5, 10, 5, 10);
        getContentPane().add(lblPeso, gbc);

        // ComboBox Peso
        comboPeso = new JComboBox<>();
        for (double i = 30; i <= 200; i += 0.5) {
            comboPeso.addItem(String.format("%.1f", i));
        }
        gbc.gridx = 1;
        getContentPane().add(comboPeso, gbc);

        // Etiqueta Altura
        gbc.gridx = 0;
        gbc.gridy = 3;
        lblAltura = new JLabel("Altura (m):");
        lblAltura.setForeground(Color.WHITE);
        getContentPane().add(lblAltura, gbc);

        // ComboBox Altura
        comboAltura = new JComboBox<>();
        for (double i = 1.3; i <= 2.2; i += 0.01) {
            comboAltura.addItem(String.format("%.2f", i));
        }
        gbc.gridx = 1;
        getContentPane().add(comboAltura, gbc);

        // Botón Calcular
        btnCalcular = new JButton("Calcular IMC");
        btnCalcular.setBackground(new Color(70, 130, 180));
        btnCalcular.setForeground(Color.WHITE);
        btnCalcular.addActionListener(e -> {calcularIMC(); excel(); generarGraficosYPDF();});
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(15, 10, 5, 10);
        getContentPane().add(btnCalcular, gbc);
        
        
        
        

        // Resultado
        lblResultado = new JLabel("Tu IMC aparecerá aquí");
        lblResultado.setForeground(Color.WHITE);
        gbc.gridy = 5;
        gbc.insets = new Insets(10, 10, 10, 10);
        getContentPane().add(lblResultado, gbc);

        // Botón Volver
        btnVolver = new JButton("Volver");
        btnVolver.setBackground(Color.DARK_GRAY);
        btnVolver.setForeground(Color.WHITE);
        btnVolver.addActionListener(e -> volverAlMenu());
        gbc.gridy = 6;
        getContentPane().add(btnVolver, gbc);

        pack();
        setLocationRelativeTo(null);
    }

    private void calcularIMC() {
         try {
        String pesoStr = comboPeso.getSelectedItem().toString().replace(',', '.');
        double peso = Double.parseDouble(pesoStr);

        String alturaStr = comboAltura.getSelectedItem().toString().replace(',', '.');
        double alturaCm = Double.parseDouble(alturaStr);
        double altura = alturaCm / 100.0; // convierte cm a metros

        double imc = peso / (altura * altura);

        String resultado = String.format("Tu IMC es: %.2f", imc);
        lblResultado.setText(resultado);
    } catch (Exception e) {
        lblResultado.setText("Error en la entrada.");
        e.printStackTrace();
    }
    }

    private void volverAlMenu() {
        Menu1 menu = new Menu1();
        menu.setVisible(true);
        this.dispose();
    }

    private void escalarTexto() {
        int ancho = getWidth();
        int alto = getHeight();
        int tamañoBase = Math.max(12, Math.min(ancho, alto) / 30);
        int tamañoTitulo = tamañoBase + 4;

        Font fuenteTitulo = new Font("Segoe UI", Font.BOLD, tamañoTitulo);
        Font fuenteNormal = new Font("Segoe UI", Font.PLAIN, tamañoBase);

        lblTitulo.setFont(fuenteTitulo);
        lblEdad.setFont(fuenteNormal);
        lblPeso.setFont(fuenteNormal);
        lblAltura.setFont(fuenteNormal);
        lblResultado.setFont(fuenteNormal);
        comboEdad.setFont(fuenteNormal);
        comboPeso.setFont(fuenteNormal);
        comboAltura.setFont(fuenteNormal);
        btnCalcular.setFont(fuenteNormal);
        btnVolver.setFont(fuenteNormal);
    }

    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new IMC1().setVisible(true));
    }

    
    // Método Excel 

    private void excel() {
        String NOMBRE_ARCHIVO = "control_datos.xlsx";
        File archivo = new File(NOMBRE_ARCHIVO);

        Workbook libroExcel = null;
        Sheet hoja = null;

        try {
            if (comboPeso.getSelectedItem() == null || comboAltura.getSelectedItem() == null || comboEdad.getSelectedItem() == null) {
                lblResultado.setText("Error: selecciona todos los valores.");
                return;
            }

            double peso = Double.parseDouble(comboPeso.getSelectedItem().toString().replace(',', '.'));
            double altura = Double.parseDouble(comboAltura.getSelectedItem().toString().replace(',', '.'));
            double imc = peso / (altura * altura);
            int edad = (int) Double.parseDouble(comboEdad.getSelectedItem().toString().replace(',', '.'));

            boolean archivoNuevo = !archivo.exists();

            if (archivo.exists()) {
                try (FileInputStream fis = new FileInputStream(archivo)) {
                    libroExcel = WorkbookFactory.create(fis);
                    hoja = libroExcel.getSheet("Datos");
                    if (hoja == null) {
                        hoja = libroExcel.createSheet("Datos");
                    }
                }
            } else {
                libroExcel = new XSSFWorkbook();
                hoja = libroExcel.createSheet("Datos");

                Row encabezado = hoja.createRow(0);
                encabezado.createCell(0).setCellValue("Fecha");
                encabezado.createCell(1).setCellValue("Hora");
                encabezado.createCell(2).setCellValue("Edad");
                encabezado.createCell(3).setCellValue("Peso (kg)");
                encabezado.createCell(4).setCellValue("Altura (m)");
                encabezado.createCell(5).setCellValue("IMC");
            }

            int numeroFila = hoja.getPhysicalNumberOfRows();
            Row fila = hoja.createRow(numeroFila);

            java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.text.SimpleDateFormat timeFormat = new java.text.SimpleDateFormat("HH:mm:ss");
            java.util.Date ahora = new java.util.Date();

            fila.createCell(0).setCellValue(dateFormat.format(ahora));
            fila.createCell(1).setCellValue(timeFormat.format(ahora));
            fila.createCell(2).setCellValue(edad);
            fila.createCell(3).setCellValue(peso);
            fila.createCell(4).setCellValue(altura);
            fila.createCell(5).setCellValue(imc);

            //️ Aplicar formato y añadir imagen solo si es un archivo nuevo
            if (archivoNuevo) {
                insertarColumnaSimple(hoja, 6, "Comentario");
                formatearHoja(hoja, libroExcel);
                String rutaImagen = "/fotos/culturista.jpg";
                if (new File(rutaImagen).exists()) {
                    insertarImagen(hoja, libroExcel, rutaImagen, 8, 1);
                }
            }

            try (FileOutputStream fos = new FileOutputStream(archivo)) {
                libroExcel.write(fos);
            }

            lblResultado.setText("Datos guardados correctamente en " + NOMBRE_ARCHIVO);

        } catch (Exception e) {
            lblResultado.setText("Error al guardar el Excel.");
            e.printStackTrace();
        } finally {
            try {
                if (libroExcel != null) libroExcel.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    
    // Funciones
   

    private void formatearHoja(Sheet hoja, Workbook libro) {
        CellStyle estiloEncabezado = libro.createCellStyle();
        CellStyle estiloNumerico = libro.createCellStyle();
        CellStyle estiloTexto = libro.createCellStyle();

        org.apache.poi.ss.usermodel.Font fuenteEncabezado = libro.createFont();
        fuenteEncabezado.setBold(true);
        fuenteEncabezado.setFontHeightInPoints((short) 12);
        estiloEncabezado.setFont(fuenteEncabezado);

        for (CellStyle estilo : new CellStyle[]{estiloEncabezado, estiloNumerico, estiloTexto}) {
            estilo.setBorderBottom(BorderStyle.THIN);
            estilo.setBorderTop(BorderStyle.THIN);
            estilo.setBorderLeft(BorderStyle.THIN);
            estilo.setBorderRight(BorderStyle.THIN);
        }

        estiloEncabezado.setAlignment(HorizontalAlignment.CENTER);
        estiloNumerico.setAlignment(HorizontalAlignment.RIGHT);
        estiloTexto.setAlignment(HorizontalAlignment.LEFT);

        DataFormat formatoDatos = libro.createDataFormat();
        estiloNumerico.setDataFormat(formatoDatos.getFormat("0.00"));

        Row encabezado = hoja.getRow(0);
        if (encabezado != null) {
            for (Cell celda : encabezado) {
                celda.setCellStyle(estiloEncabezado);
            }
        }

        for (int i = 1; i <= hoja.getLastRowNum(); i++) {
            Row fila = hoja.getRow(i);
            if (fila != null) {
                for (int j = 0; j < fila.getLastCellNum(); j++) {
                    Cell celda = fila.getCell(j);
                    if (celda != null) {
                        if (celda.getCellType() == CellType.NUMERIC) {
                            celda.setCellStyle(estiloNumerico);
                        } else {
                            celda.setCellStyle(estiloTexto);
                        }
                    }
                }
            }
        }

        for (int col = 0; col < hoja.getRow(0).getLastCellNum(); col++) {
            hoja.autoSizeColumn(col);
        }
    }

    private void insertarColumnaSimple(Sheet hoja, int indiceColumna, String tituloColumna) {
        if (hoja == null) return;
        Row filaEncabezado = hoja.getRow(0);
        if (filaEncabezado == null) {
            filaEncabezado = hoja.createRow(0);
        }
        Cell celda = filaEncabezado.createCell(indiceColumna);
        celda.setCellValue(tituloColumna);
        hoja.autoSizeColumn(indiceColumna);
    }

   private void insertarImagen(Sheet hoja, Workbook libro, String rutaRecurso, int columna, int fila) {
    try (InputStream imagenStream = getClass().getResourceAsStream(rutaRecurso)) {
        if (imagenStream == null) {
            System.out.println("No se encontró la imagen en el recurso: " + rutaRecurso);
            return;
        }

        byte[] bytesImagen = IOUtils.toByteArray(imagenStream);
        int indiceImagen = libro.addPicture(bytesImagen, Workbook.PICTURE_TYPE_JPEG); // o PNG si usas .png

        CreationHelper helper = libro.getCreationHelper();
        Drawing<?> dibujo = hoja.createDrawingPatriarch();

        ClientAnchor anchor = helper.createClientAnchor();
        anchor.setCol1(columna);
        anchor.setRow1(fila);
        anchor.setCol2(columna + 2);
        anchor.setRow2(fila + 4);

        dibujo.createPicture(anchor, indiceImagen);

        System.out.println("Imagen insertada correctamente desde el recurso: " + rutaRecurso);
    } catch (IOException e) {
        System.out.println("Error al insertar la imagen desde el recurso");
        e.printStackTrace();
    }
}

//  Graficos Excel
   
private void generarGraficosDesdeExcel() {
    try (FileInputStream fis = new FileInputStream("control_datos.xlsx");
         Workbook libro = WorkbookFactory.create(fis)) {

        Sheet hoja = libro.getSheet("Datos");
        if (hoja == null || hoja.getPhysicalNumberOfRows() <= 1) {
            System.out.println("No hay datos suficientes para generar gráficos.");
            return;
        }

        org.jfree.data.category.DefaultCategoryDataset datasetBarras = new org.jfree.data.category.DefaultCategoryDataset();
        org.jfree.data.general.DefaultPieDataset<String> datasetCircular = new org.jfree.data.general.DefaultPieDataset<>();

        for (int i = 1; i < hoja.getPhysicalNumberOfRows(); i++) {
            Row fila = hoja.getRow(i);
            if (fila == null) continue;
            String fecha = fila.getCell(0).getStringCellValue();
            double imc = fila.getCell(5).getNumericCellValue();
            datasetBarras.addValue(imc, "IMC", fecha);
            datasetCircular.setValue(fecha, imc);
        }

        //Gráfico de Barras
        org.jfree.chart.JFreeChart chartBarras = org.jfree.chart.ChartFactory.createBarChart(
                "Evolución del IMC",
                "Fecha",
                "IMC",
                datasetBarras
        );
        org.jfree.chart.ChartUtils.saveChartAsJPEG(new File("grafico_barras.jpg"), chartBarras, 600, 400);

        // ====== Gráfico de Líneas ======
        org.jfree.chart.JFreeChart chartLineas = org.jfree.chart.ChartFactory.createLineChart(
                "IMC a lo largo del tiempo",
                "Fecha",
                "IMC",
                datasetBarras
        );
        org.jfree.chart.ChartUtils.saveChartAsJPEG(new File("grafico_lineas.jpg"), chartLineas, 600, 400);

        // ====== Gráfico Circular ======
        org.jfree.chart.JFreeChart chartCircular = org.jfree.chart.ChartFactory.createPieChart(
                "Distribución del IMC",
                datasetCircular,
                true, true, false
        );
        org.jfree.chart.ChartUtils.saveChartAsJPEG(new File("grafico_circular.jpg"), chartCircular, 600, 400);

        System.out.println("Gráficos creados y guardados como imágenes .jpg");

    } catch (Exception e) {
        e.printStackTrace();
    }
}


// Función crear pdf

private void generarInformePDF() {
    try {
        com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new FileOutputStream("informe_IMC.pdf"));
        documento.open();

        documento.add(new com.itextpdf.text.Paragraph("Informe de IMC - Deporte y Salud"));
        documento.add(new com.itextpdf.text.Paragraph(" "));
        documento.add(new com.itextpdf.text.Paragraph("Gráficos generados:"));
        documento.add(new com.itextpdf.text.Paragraph(" "));

        // Añadimos las imágenes si existen
        String[] imagenes = {"grafico_barras.jpg", "grafico_lineas.jpg", "grafico_circular.jpg"};
        for (String imgPath : imagenes) {
            File imgFile = new File(imgPath);
            if (imgFile.exists()) {
                com.itextpdf.text.Image img = com.itextpdf.text.Image.getInstance(imgPath);
                img.scaleToFit(500, 300);
                documento.add(img);
                documento.add(new com.itextpdf.text.Paragraph(" "));
            }
        }

        documento.add(new com.itextpdf.text.Paragraph("Fecha del informe: " +
                new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm").format(new java.util.Date())));

        documento.close();
        System.out.println("Informe PDF generado correctamente.");

    } catch (Exception e) {
        e.printStackTrace();
    }
}


// Función para usar las funciones de gráficos y pdf

private void generarGraficosYPDF() {
    generarGraficosDesdeExcel();
    generarInformePDF();
}

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

